# Generated by Django 4.0 on 2024-07-23 10:21

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('sexe', models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('photo_profile', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dep', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('host_user', models.CharField(max_length=255)),
                ('host_password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('secteurActivite', models.CharField(max_length=100)),
                ('site_web', models.URLField(blank=True, max_length=255)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_role', models.CharField(max_length=50)),
                ('niv_permission', models.IntegerField()),
                ('acce_page', models.CharField(blank=True, choices=[('AD', 'Page administrateur'), ('SA', 'Page salarié'), ('EN', 'Page des partenaires'), ('CL', 'Page des clients')], max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salarie', models.CharField(max_length=100)),
                ('prenom_salarie', models.CharField(max_length=150)),
                ('dateNaissance', models.DateField(blank=True, null=True)),
                ('dateEmbauche', models.DateTimeField(blank=True, null=True)),
                ('annee_exp', models.PositiveIntegerField(null=True)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.compte')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.departement')),
            ],
        ),
        migrations.CreateModel(
            name='FicheDePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePaiement', models.DateField()),
                ('echeance', models.DateField()),
                ('detail', models.TextField()),
                ('montant', models.FloatField()),
                ('statut', models.CharField(default='Impayer', max_length=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entreprise')),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('competences_recherchees', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDÉ', 'Validé'), ('REFUSÉ', 'Refusé')], default='EN_ATTENTE', max_length=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_contrat', models.CharField(max_length=100)),
                ('fonction_salarie', models.CharField(blank=True, max_length=100, null=True)),
                ('mode_paiement', models.CharField(choices=[('H', 'Heure'), ('J', 'Jour'), ('M', 'Mois')], max_length=50)),
                ('taux_horaire', models.FloatField(blank=True, null=True)),
                ('heures_travail', models.IntegerField(blank=True, null=True)),
                ('jours_travail', models.IntegerField(blank=True, null=True)),
                ('salaire_mensuel', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(default='En cours', max_length=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entreprise')),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salarie')),
            ],
        ),
        migrations.AddField(
            model_name='compte',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.role'),
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(blank=True, max_length=100, null=True)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('prenom_client', models.CharField(max_length=150)),
                ('poste_occupe', models.CharField(max_length=100)),
                ('compte', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.compte')),
                ('entreprise_affilier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause', models.TextField(blank=True, null=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contrat')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_admin', models.CharField(max_length=100)),
                ('prenom_admin', models.CharField(max_length=150)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.compte')),
            ],
        ),
    ]
