# Generated by Django 4.0 on 2024-07-23 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contrat_client_alter_client_entreprise_affilier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='dateFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='poste',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom_client',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='prenom_salarie',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePaiement', models.DateField()),
                ('echeance', models.DateField()),
                ('detail', models.TextField()),
                ('montant', models.FloatField()),
                ('statut', models.CharField(default='Impayer', max_length=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entreprise')),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='FicheDePaieContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePaiement', models.DateField()),
                ('echeance', models.DateField()),
                ('detail', models.TextField()),
                ('montant', models.FloatField()),
                ('statut', models.CharField(default='Impayer', max_length=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entreprise')),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salarie')),
            ],
        ),
    ]
