# Generated by Django 4.0 on 2024-07-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_salarie_datefin_salarie_poste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarie',
            name='dateEmbauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='dateFin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
