# Generated by Django 4.0 on 2024-07-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_salarie_dateembauche_alter_salarie_datefin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='fichedepaie',
            name='datePaiement',
        ),
        migrations.RemoveField(
            model_name='fichedepaie',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='fichedepaie',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='dateEmbauche',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='dateFin',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='poste',
        ),
        migrations.AddField(
            model_name='contrat',
            name='est_terminer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrat',
            name='taux_journalier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='a_periode',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='dateEmission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='est_payer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='nbre_jour_conger',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='nbre_jour_travail',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='periode_de',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='salaire_net',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='total_indemnite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='total_prime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='total_retenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='travail_nuit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='travail_supp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichedepaie',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fichedepaie',
            name='echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FicheDePaieContrat',
        ),
    ]
