# Generated by Django 4.0 on 2024-07-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_contrat_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='nom_agent_entreprise',
            field=models.CharField(default='Aucun', max_length=100),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='poste_agent',
            field=models.CharField(default='Agent', max_length=200),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='prenom_agent_entreprise',
            field=models.CharField(default='Aucun', max_length=200),
        ),
    ]
