# Generated by Django 4.0 on 2024-07-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=50)),
                ('mot_de_passe', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo_profile', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dep', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('dateNaissance', models.DateField()),
                ('dateEmbauche', models.DateTimeField(auto_now_add=True)),
                ('annee_exp', models.PositiveIntegerField(null=True)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.compte')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_role', models.CharField(max_length=50)),
                ('niv_permission', models.IntegerField()),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.departement')),
            ],
        ),
        migrations.CreateModel(
            name='FicheDePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePaiement', models.DateField()),
                ('montant', models.FloatField()),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('secteurActivite', models.CharField(max_length=100)),
                ('site_web', models.URLField(blank=True, max_length=255)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.compte')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('competences_recherchees', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDÉ', 'Validé'), ('REFUSÉ', 'Refusé')], default='EN_ATTENTE', max_length=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_contrat', models.CharField(max_length=100)),
                ('mode_paiement', models.CharField(choices=[('H', 'Heure'), ('J', 'Jour'), ('M', 'Mois')], max_length=50)),
                ('taux_horaire', models.FloatField(blank=True, null=True)),
                ('heures_travail', models.IntegerField(blank=True, null=True)),
                ('jours_travail', models.IntegerField(blank=True, null=True)),
                ('salaire_mensuel', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('terminer', 'Terminer')], max_length=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entreprise')),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salarie')),
            ],
        ),
        migrations.AddField(
            model_name='compte',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.role'),
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(max_length=100)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.compte')),
            ],
        ),
    ]
