# Generated by Django 4.0 on 2024-07-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='sexe',
            field=models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('nom_prenom', models.CharField(max_length=150)),
                ('poste_occupe', models.CharField(max_length=100)),
                ('entreprise_affilier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entreprise')),
            ],
        ),
    ]
