# Generated by Django 4.0 on 2024-07-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='nom',
            new_name='nom_admin',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='prenom',
            new_name='prenom_admin',
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='nom',
            new_name='nom_entreprise',
        ),
        migrations.RenameField(
            model_name='salarie',
            old_name='nom',
            new_name='nom_salarie',
        ),
        migrations.RenameField(
            model_name='salarie',
            old_name='prenom',
            new_name='prenom_salarie',
        ),
    ]
