# Generated by Django 4.0 on 2024-07-12 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_compte_sexe_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='compte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.compte'),
        ),
    ]
