# Generated by Django 4.0 on 2024-07-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_client_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='acce_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
