# Generated by Django 4.0 on 2024-07-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_role_acce_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='acce_page',
            field=models.CharField(blank=True, choices=[('AD', 'Page administrateur'), ('SA', 'Page salarié'), ('CL', 'Page des clients')], max_length=60, null=True),
        ),
    ]
