# Generated by Django 4.0 on 2024-07-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_role_acce_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='competence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compte',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='dateEmbauche',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
