# Generated by Django 4.0 on 2024-07-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_competence_competence_alter_compte_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='statut',
        ),
        migrations.AddField(
            model_name='compte',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
