# Generated by Django 4.0 on 2024-07-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_compte_statut_compte_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nom_prenom',
            new_name='prenom_client',
        ),
    ]
