# Generated by Django 4.0 on 2024-07-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_nom_prenom_client_prenom_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='acce_page',
            field=models.CharField(blank=True, choices=[('AD', 'Page administrateur'), ('SA', 'Page salarié'), ('EN', 'Page des partenaires'), ('CL', 'Page des clients')], max_length=60, null=True),
        ),
    ]
