# Generated by Django 4.0 on 2024-07-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_role_acce_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='departement',
        ),
    ]
