# Generated by Django 4.0 on 2024-07-22 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_emailsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichedepaie',
            name='salarie',
        ),
        migrations.AddField(
            model_name='contrat',
            name='fonction_salarie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='contrat',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.contrat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause', models.TextField(blank=True, null=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contrat')),
            ],
        ),
    ]
