# Generated by Django 4.0 on 2024-07-22 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_fichedepaie_salarie_contrat_fonction_salarie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichedepaie',
            name='echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='statut',
            field=models.CharField(default='Impayer', max_length=10),
        ),
        migrations.AlterField(
            model_name='fichedepaie',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contrat'),
        ),
    ]
